import type * as MonacoNs from "monaco-editor";

/**
 * Semantic palette used to generate a full Monaco theme. Adding a new theme
 * is just a matter of filling out one of these objects — the generator does
 * the rest. Colors are hex without `#`.
 */
export type ThemePalette = {
  base: "vs" | "vs-dark";
  bg: string;
  bgElev: string;
  bgGutter: string;
  fg: string;
  fgMuted: string;
  fgDim: string;
  selection: string;
  selectionMatch: string;
  lineHighlight: string;
  cursor: string;

  // Syntax
  comment: string;
  string: string;
  stringEscape: string;
  number: string;
  keyword: string;
  keywordControl: string;
  operator: string;
  type: string;
  function: string;
  variable: string;
  variableProp: string;
  constant: string;
  tag: string;
  attribute: string;
  regex: string;

  // Diff colors
  diffAdded: string;
  diffRemoved: string;
};

export const PALETTES: Record<string, ThemePalette> = {
  // ─── Catppuccin ─────────────────────────────────────────────────────────
  "catppuccin-mocha": {
    base: "vs-dark",
    bg: "1E1E2E",
    bgElev: "181825",
    bgGutter: "1E1E2E",
    fg: "CDD6F4",
    fgMuted: "BAC2DE",
    fgDim: "6C7086",
    selection: "585B7066",
    selectionMatch: "585B7044",
    lineHighlight: "313244",
    cursor: "F5E0DC",
    comment: "6C7086",
    string: "A6E3A1",
    stringEscape: "F2CDCD",
    number: "FAB387",
    keyword: "CBA6F7",
    keywordControl: "F38BA8",
    operator: "89DCEB",
    type: "F9E2AF",
    function: "89B4FA",
    variable: "CDD6F4",
    variableProp: "94E2D5",
    constant: "FAB387",
    tag: "F38BA8",
    attribute: "F9E2AF",
    regex: "F5C2E7",
    diffAdded: "A6E3A122",
    diffRemoved: "F38BA822",
  },
  "catppuccin-macchiato": {
    base: "vs-dark",
    bg: "24273A",
    bgElev: "1E2030",
    bgGutter: "24273A",
    fg: "CAD3F5",
    fgMuted: "B8C0E0",
    fgDim: "6E738D",
    selection: "5B607866",
    selectionMatch: "5B607844",
    lineHighlight: "363A4F",
    cursor: "F4DBD6",
    comment: "6E738D",
    string: "A6DA95",
    stringEscape: "F0C6C6",
    number: "F5A97F",
    keyword: "C6A0F6",
    keywordControl: "ED8796",
    operator: "91D7E3",
    type: "EED49F",
    function: "8AADF4",
    variable: "CAD3F5",
    variableProp: "8BD5CA",
    constant: "F5A97F",
    tag: "ED8796",
    attribute: "EED49F",
    regex: "F5BDE6",
    diffAdded: "A6DA9522",
    diffRemoved: "ED879622",
  },
  "catppuccin-frappe": {
    base: "vs-dark",
    bg: "303446",
    bgElev: "292C3C",
    bgGutter: "303446",
    fg: "C6D0F5",
    fgMuted: "B5BFE2",
    fgDim: "737994",
    selection: "62688066",
    selectionMatch: "62688044",
    lineHighlight: "414559",
    cursor: "F2D5CF",
    comment: "737994",
    string: "A6D189",
    stringEscape: "F2D5CF",
    number: "EF9F76",
    keyword: "CA9EE6",
    keywordControl: "E78284",
    operator: "99D1DB",
    type: "E5C890",
    function: "8CAAEE",
    variable: "C6D0F5",
    variableProp: "81C8BE",
    constant: "EF9F76",
    tag: "E78284",
    attribute: "E5C890",
    regex: "F4B8E4",
    diffAdded: "A6D18922",
    diffRemoved: "E7828422",
  },
  "catppuccin-latte": {
    base: "vs",
    bg: "EFF1F5",
    bgElev: "E6E9EF",
    bgGutter: "EFF1F5",
    fg: "4C4F69",
    fgMuted: "5C5F77",
    fgDim: "9CA0B0",
    selection: "ACB0BE66",
    selectionMatch: "ACB0BE44",
    lineHighlight: "DCE0E8",
    cursor: "DC8A78",
    comment: "9CA0B0",
    string: "40A02B",
    stringEscape: "DC8A78",
    number: "FE640B",
    keyword: "8839EF",
    keywordControl: "D20F39",
    operator: "04A5E5",
    type: "DF8E1D",
    function: "1E66F5",
    variable: "4C4F69",
    variableProp: "179299",
    constant: "FE640B",
    tag: "D20F39",
    attribute: "DF8E1D",
    regex: "EA76CB",
    diffAdded: "40A02B22",
    diffRemoved: "D20F3922",
  },

  // ─── Dracula ────────────────────────────────────────────────────────────
  dracula: {
    base: "vs-dark",
    bg: "282A36",
    bgElev: "21222C",
    bgGutter: "282A36",
    fg: "F8F8F2",
    fgMuted: "BFBFBF",
    fgDim: "6272A4",
    selection: "44475A99",
    selectionMatch: "44475A55",
    lineHighlight: "44475A55",
    cursor: "F8F8F2",
    comment: "6272A4",
    string: "F1FA8C",
    stringEscape: "FFB86C",
    number: "BD93F9",
    keyword: "FF79C6",
    keywordControl: "FF79C6",
    operator: "FF79C6",
    type: "8BE9FD",
    function: "50FA7B",
    variable: "F8F8F2",
    variableProp: "FFB86C",
    constant: "BD93F9",
    tag: "FF79C6",
    attribute: "50FA7B",
    regex: "F1FA8C",
    diffAdded: "50FA7B22",
    diffRemoved: "FF555522",
  },

  // ─── Tokyo Night (real, not vs-dark stub) ────────────────────────────────
  "tokyo-night": {
    base: "vs-dark",
    bg: "1A1B26",
    bgElev: "16161E",
    bgGutter: "1A1B26",
    fg: "C0CAF5",
    fgMuted: "A9B1D6",
    fgDim: "565F89",
    selection: "33467C99",
    selectionMatch: "33467C55",
    lineHighlight: "292E42",
    cursor: "C0CAF5",
    comment: "565F89",
    string: "9ECE6A",
    stringEscape: "E0AF68",
    number: "FF9E64",
    keyword: "BB9AF7",
    keywordControl: "F7768E",
    operator: "89DDFF",
    type: "2AC3DE",
    function: "7AA2F7",
    variable: "C0CAF5",
    variableProp: "73DACA",
    constant: "FF9E64",
    tag: "F7768E",
    attribute: "E0AF68",
    regex: "B4F9F8",
    diffAdded: "9ECE6A22",
    diffRemoved: "F7768E22",
  },

  // ─── Nord (real) ────────────────────────────────────────────────────────
  nord: {
    base: "vs-dark",
    bg: "2E3440",
    bgElev: "272B35",
    bgGutter: "2E3440",
    fg: "D8DEE9",
    fgMuted: "C0C7D5",
    fgDim: "4C566A",
    selection: "434C5E99",
    selectionMatch: "434C5E55",
    lineHighlight: "3B4252",
    cursor: "D8DEE9",
    comment: "616E88",
    string: "A3BE8C",
    stringEscape: "EBCB8B",
    number: "B48EAD",
    keyword: "81A1C1",
    keywordControl: "81A1C1",
    operator: "81A1C1",
    type: "8FBCBB",
    function: "88C0D0",
    variable: "D8DEE9",
    variableProp: "8FBCBB",
    constant: "B48EAD",
    tag: "81A1C1",
    attribute: "8FBCBB",
    regex: "EBCB8B",
    diffAdded: "A3BE8C22",
    diffRemoved: "BF616A22",
  },

  // ─── Rose Pine ──────────────────────────────────────────────────────────
  "rose-pine": {
    base: "vs-dark",
    bg: "191724",
    bgElev: "1F1D2E",
    bgGutter: "191724",
    fg: "E0DEF4",
    fgMuted: "908CAA",
    fgDim: "6E6A86",
    selection: "403D5266",
    selectionMatch: "403D5244",
    lineHighlight: "26233A",
    cursor: "E0DEF4",
    comment: "6E6A86",
    string: "F6C177",
    stringEscape: "EBBCBA",
    number: "EBBCBA",
    keyword: "C4A7E7",
    keywordControl: "EB6F92",
    operator: "9CCFD8",
    type: "F6C177",
    function: "EBBCBA",
    variable: "E0DEF4",
    variableProp: "9CCFD8",
    constant: "C4A7E7",
    tag: "EB6F92",
    attribute: "F6C177",
    regex: "9CCFD8",
    diffAdded: "31748F22",
    diffRemoved: "EB6F9222",
  },

  // ─── One Dark Pro ───────────────────────────────────────────────────────
  "one-dark-pro": {
    base: "vs-dark",
    bg: "282C34",
    bgElev: "21252B",
    bgGutter: "282C34",
    fg: "ABB2BF",
    fgMuted: "9DA5B4",
    fgDim: "5C6370",
    selection: "3E445199",
    selectionMatch: "3E445155",
    lineHighlight: "2C313C",
    cursor: "528BFF",
    comment: "5C6370",
    string: "98C379",
    stringEscape: "56B6C2",
    number: "D19A66",
    keyword: "C678DD",
    keywordControl: "C678DD",
    operator: "56B6C2",
    type: "E5C07B",
    function: "61AFEF",
    variable: "E06C75",
    variableProp: "ABB2BF",
    constant: "D19A66",
    tag: "E06C75",
    attribute: "D19A66",
    regex: "56B6C2",
    diffAdded: "98C37922",
    diffRemoved: "E06C7522",
  },

  // ─── Solarized ──────────────────────────────────────────────────────────
  "solarized-dark": {
    base: "vs-dark",
    bg: "002B36",
    bgElev: "00212B",
    bgGutter: "002B36",
    fg: "839496",
    fgMuted: "93A1A1",
    fgDim: "586E75",
    selection: "07364299",
    selectionMatch: "07364255",
    lineHighlight: "073642",
    cursor: "93A1A1",
    comment: "586E75",
    string: "2AA198",
    stringEscape: "B58900",
    number: "D33682",
    keyword: "859900",
    keywordControl: "CB4B16",
    operator: "839496",
    type: "B58900",
    function: "268BD2",
    variable: "839496",
    variableProp: "6C71C4",
    constant: "D33682",
    tag: "268BD2",
    attribute: "B58900",
    regex: "DC322F",
    diffAdded: "85990022",
    diffRemoved: "DC322F22",
  },
  "solarized-light": {
    base: "vs",
    bg: "FDF6E3",
    bgElev: "EEE8D5",
    bgGutter: "FDF6E3",
    fg: "657B83",
    fgMuted: "586E75",
    fgDim: "93A1A1",
    selection: "EEE8D599",
    selectionMatch: "EEE8D555",
    lineHighlight: "EEE8D5",
    cursor: "586E75",
    comment: "93A1A1",
    string: "2AA198",
    stringEscape: "B58900",
    number: "D33682",
    keyword: "859900",
    keywordControl: "CB4B16",
    operator: "657B83",
    type: "B58900",
    function: "268BD2",
    variable: "657B83",
    variableProp: "6C71C4",
    constant: "D33682",
    tag: "268BD2",
    attribute: "B58900",
    regex: "DC322F",
    diffAdded: "85990022",
    diffRemoved: "DC322F22",
  },

  // ─── Monokai ────────────────────────────────────────────────────────────
  monokai: {
    base: "vs-dark",
    bg: "272822",
    bgElev: "1E1F1C",
    bgGutter: "272822",
    fg: "F8F8F2",
    fgMuted: "CFCFC2",
    fgDim: "75715E",
    selection: "49483E99",
    selectionMatch: "49483E55",
    lineHighlight: "3E3D32",
    cursor: "F8F8F0",
    comment: "75715E",
    string: "E6DB74",
    stringEscape: "AE81FF",
    number: "AE81FF",
    keyword: "F92672",
    keywordControl: "F92672",
    operator: "F92672",
    type: "66D9EF",
    function: "A6E22E",
    variable: "F8F8F2",
    variableProp: "FD971F",
    constant: "AE81FF",
    tag: "F92672",
    attribute: "A6E22E",
    regex: "FD971F",
    diffAdded: "A6E22E22",
    diffRemoved: "F9267222",
  },

  // ─── GitHub ─────────────────────────────────────────────────────────────
  "github-dark": {
    base: "vs-dark",
    bg: "0D1117",
    bgElev: "010409",
    bgGutter: "0D1117",
    fg: "C9D1D9",
    fgMuted: "B1BAC4",
    fgDim: "8B949E",
    selection: "264F7899",
    selectionMatch: "264F7855",
    lineHighlight: "161B22",
    cursor: "C9D1D9",
    comment: "8B949E",
    string: "A5D6FF",
    stringEscape: "FFA657",
    number: "79C0FF",
    keyword: "FF7B72",
    keywordControl: "FF7B72",
    operator: "FF7B72",
    type: "FFA657",
    function: "D2A8FF",
    variable: "C9D1D9",
    variableProp: "79C0FF",
    constant: "79C0FF",
    tag: "7EE787",
    attribute: "79C0FF",
    regex: "7EE787",
    diffAdded: "23863622",
    diffRemoved: "DA363322",
  },
  "github-light": {
    base: "vs",
    bg: "FFFFFF",
    bgElev: "F6F8FA",
    bgGutter: "FFFFFF",
    fg: "1F2328",
    fgMuted: "656D76",
    fgDim: "8C959F",
    selection: "0969DA22",
    selectionMatch: "0969DA11",
    lineHighlight: "F6F8FA",
    cursor: "1F2328",
    comment: "6E7781",
    string: "0A3069",
    stringEscape: "953800",
    number: "0550AE",
    keyword: "CF222E",
    keywordControl: "CF222E",
    operator: "CF222E",
    type: "953800",
    function: "8250DF",
    variable: "1F2328",
    variableProp: "0550AE",
    constant: "0550AE",
    tag: "116329",
    attribute: "0550AE",
    regex: "116329",
    diffAdded: "1A7F3722",
    diffRemoved: "CF222E22",
  },
};

export type ThemeId = keyof typeof PALETTES;

export const THEME_LABELS: Record<ThemeId, string> = {
  "catppuccin-mocha": "Catppuccin Mocha",
  "catppuccin-macchiato": "Catppuccin Macchiato",
  "catppuccin-frappe": "Catppuccin Frappé",
  "catppuccin-latte": "Catppuccin Latte",
  dracula: "Dracula",
  "tokyo-night": "Tokyo Night",
  nord: "Nord",
  "rose-pine": "Rosé Pine",
  "one-dark-pro": "One Dark Pro",
  "solarized-dark": "Solarized Dark",
  "solarized-light": "Solarized Light",
  monokai: "Monokai",
  "github-dark": "GitHub Dark",
  "github-light": "GitHub Light",
};

export const THEME_IDS = Object.keys(PALETTES) as ThemeId[];

/**
 * Best-effort detection of whether a theme should be considered "light" for
 * UI surfaces that adapt to the editor (gutter chrome, etc.).
 */
export function isLightTheme(id: ThemeId): boolean {
  return PALETTES[id].base === "vs";
}

/** Build a Monaco theme definition from a palette. */
export function buildTheme(p: ThemePalette): MonacoNs.editor.IStandaloneThemeData {
  return {
    base: p.base,
    inherit: true,
    rules: [
      { token: "comment", foreground: p.comment, fontStyle: "italic" },
      { token: "string", foreground: p.string },
      { token: "string.escape", foreground: p.stringEscape },
      { token: "number", foreground: p.number },
      { token: "constant", foreground: p.constant },
      { token: "constant.numeric", foreground: p.number },
      { token: "constant.language", foreground: p.constant },
      { token: "keyword", foreground: p.keyword },
      { token: "keyword.control", foreground: p.keywordControl },
      { token: "keyword.operator", foreground: p.operator },
      { token: "operator", foreground: p.operator },
      { token: "type", foreground: p.type },
      { token: "type.identifier", foreground: p.type },
      { token: "namespace", foreground: p.type },
      { token: "class", foreground: p.type },
      { token: "interface", foreground: p.type },
      { token: "struct", foreground: p.type },
      { token: "enum", foreground: p.type },
      { token: "function", foreground: p.function },
      { token: "variable", foreground: p.variable },
      { token: "variable.parameter", foreground: p.variable },
      { token: "variable.predefined", foreground: p.variableProp },
      { token: "tag", foreground: p.tag },
      { token: "tag.id", foreground: p.variable },
      { token: "attribute.name", foreground: p.attribute },
      { token: "attribute.value", foreground: p.string },
      { token: "delimiter", foreground: p.fg },
      { token: "delimiter.bracket", foreground: p.fg },
      { token: "metatag", foreground: p.tag },
      { token: "regexp", foreground: p.regex },
      { token: "annotation", foreground: p.function },
      { token: "key", foreground: p.variable },
      { token: "string.key.json", foreground: p.tag },
      { token: "string.value.json", foreground: p.string },
    ],
    colors: {
      "editor.background": `#${p.bg}`,
      "editor.foreground": `#${p.fg}`,
      "editor.lineHighlightBackground": `#${p.lineHighlight}`,
      "editor.lineHighlightBorder": "#00000000",
      "editor.selectionBackground": `#${p.selection}`,
      "editor.selectionHighlightBackground": `#${p.selectionMatch}`,
      "editorCursor.foreground": `#${p.cursor}`,
      "editorWhitespace.foreground": `#${p.fgDim}`,
      "editorIndentGuide.background": `#${p.bgElev}`,
      "editorIndentGuide.activeBackground": `#${p.fgDim}`,
      "editorLineNumber.foreground": `#${p.fgDim}`,
      "editorLineNumber.activeForeground": `#${p.fgMuted}`,
      "editorGutter.background": `#${p.bgGutter}`,
      "editorWidget.background": `#${p.bgElev}`,
      "editorWidget.border": `#${p.bgElev}`,
      "editorSuggestWidget.background": `#${p.bgElev}`,
      "editorSuggestWidget.border": `#${p.bgElev}`,
      "editorSuggestWidget.selectedBackground": `#${p.selection}`,
      "editorHoverWidget.background": `#${p.bgElev}`,
      "editorHoverWidget.border": `#${p.bgElev}`,
      "scrollbarSlider.background": `#${p.fgDim}33`,
      "scrollbarSlider.hoverBackground": `#${p.fgDim}66`,
      "scrollbarSlider.activeBackground": `#${p.fgDim}99`,
      "diffEditor.insertedTextBackground": `#${p.diffAdded}`,
      "diffEditor.removedTextBackground": `#${p.diffRemoved}`,
    },
  };
}
