import type * as MonacoNs from "monaco-editor";

// Hand-crafted "VS Code Dark+" approximation. Hex values lifted from the
// open-source Default Dark+ theme (vscode/extensions/theme-defaults).
export const VSCODE_DARK: MonacoNs.editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "6A9955", fontStyle: "italic" },
    { token: "string", foreground: "CE9178" },
    { token: "string.escape", foreground: "D7BA7D" },
    { token: "number", foreground: "B5CEA8" },
    { token: "constant", foreground: "4FC1FF" },
    { token: "constant.numeric", foreground: "B5CEA8" },
    { token: "constant.language", foreground: "569CD6" },
    { token: "keyword", foreground: "569CD6" },
    { token: "keyword.control", foreground: "C586C0" },
    { token: "keyword.operator", foreground: "D4D4D4" },
    { token: "operator", foreground: "D4D4D4" },
    { token: "type", foreground: "4EC9B0" },
    { token: "type.identifier", foreground: "4EC9B0" },
    { token: "namespace", foreground: "4EC9B0" },
    { token: "class", foreground: "4EC9B0" },
    { token: "interface", foreground: "4EC9B0" },
    { token: "struct", foreground: "4EC9B0" },
    { token: "enum", foreground: "4EC9B0" },
    { token: "function", foreground: "DCDCAA" },
    { token: "variable", foreground: "9CDCFE" },
    { token: "variable.parameter", foreground: "9CDCFE" },
    { token: "variable.predefined", foreground: "4FC1FF" },
    { token: "tag", foreground: "569CD6" },
    { token: "tag.id", foreground: "9CDCFE" },
    { token: "attribute.name", foreground: "9CDCFE" },
    { token: "attribute.value", foreground: "CE9178" },
    { token: "delimiter", foreground: "D4D4D4" },
    { token: "delimiter.bracket", foreground: "D4D4D4" },
    { token: "metatag", foreground: "569CD6" },
    { token: "regexp", foreground: "D16969" },
    { token: "annotation", foreground: "DCDCAA" },
    // markdown
    { token: "key", foreground: "9CDCFE" },
    { token: "string.key.json", foreground: "9CDCFE" },
    { token: "string.value.json", foreground: "CE9178" },
  ],
  colors: {
    "editor.background": "#1E1E1E",
    "editor.foreground": "#D4D4D4",
    "editor.lineHighlightBackground": "#2A2D2E",
    "editor.lineHighlightBorder": "#00000000",
    "editor.selectionBackground": "#264F78",
    "editor.selectionHighlightBackground": "#ADD6FF26",
    "editor.findMatchBackground": "#515C6A",
    "editor.findMatchHighlightBackground": "#EA5C0055",
    "editor.wordHighlightBackground": "#575757B8",
    "editor.wordHighlightStrongBackground": "#004972B8",
    "editorCursor.foreground": "#AEAFAD",
    "editorWhitespace.foreground": "#404040",
    "editorIndentGuide.background": "#404040",
    "editorIndentGuide.activeBackground": "#707070",
    "editorLineNumber.foreground": "#858585",
    "editorLineNumber.activeForeground": "#C6C6C6",
    "editorBracketMatch.background": "#0064001A",
    "editorBracketMatch.border": "#888888",
    "editorGutter.background": "#1E1E1E",
    "editorGutter.modifiedBackground": "#1B81A8",
    "editorGutter.addedBackground": "#487E02",
    "editorGutter.deletedBackground": "#F44747",
    "editorWidget.background": "#252526",
    "editorWidget.border": "#454545",
    "editorSuggestWidget.background": "#252526",
    "editorSuggestWidget.border": "#454545",
    "editorSuggestWidget.selectedBackground": "#04395E",
    "editorHoverWidget.background": "#252526",
    "editorHoverWidget.border": "#454545",
    "scrollbarSlider.background": "#79797966",
    "scrollbarSlider.hoverBackground": "#646464B3",
    "scrollbarSlider.activeBackground": "#BFBFBF66",
    "diffEditor.insertedTextBackground": "#9bb955_22",
    "diffEditor.removedTextBackground": "#ff000033",
  },
};

export const VSCODE_LIGHT: MonacoNs.editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "comment", foreground: "008000", fontStyle: "italic" },
    { token: "string", foreground: "A31515" },
    { token: "number", foreground: "098658" },
    { token: "keyword", foreground: "0000FF" },
    { token: "keyword.control", foreground: "AF00DB" },
    { token: "type", foreground: "267F99" },
    { token: "function", foreground: "795E26" },
    { token: "variable", foreground: "001080" },
    { token: "tag", foreground: "800000" },
    { token: "attribute.name", foreground: "FF0000" },
    { token: "attribute.value", foreground: "0451A5" },
  ],
  colors: {
    "editor.background": "#FFFFFF",
    "editor.foreground": "#000000",
    "editor.lineHighlightBackground": "#F3F3F3",
    "editorCursor.foreground": "#000000",
    "editorLineNumber.foreground": "#237893",
    "editorLineNumber.activeForeground": "#0B216F",
  },
};
